gpu: 'cuda:0'
---
feature: 'MFCC' # MFCC
---
model:
  type: 'SKDAE' #  FC, SKDAE
  target: 'estim' # noisy, estim
  activation : 'sigmoid' # sigmoid, tanh
  version : 2
  context : 6  # ( conext...  target conext... )
  feature_size : 13
---
train:
  epoch: 150
  batch_size: 128
  num_workers: 16
  summary_interval: 10
  validation_interval: 100
  checkpoint_interval: 1000
---
loss:
  type: 'MSE' # MSE, L1
---
optim:
  type: "Adam" # Adam
  adam: 0.0001
  adabound:
    initial: 0.001
    final: 0.05
---
scheduler: 
  type: 'Plateau' # Plateau, oneCycle, None
  oneCycle:
    max_lr: 0.0001
  Plateau:
    mode: 'min'
    patience: 2
    factor: 0.5
    min_lr: 0.000005
---
audio:
  frame : 400
  shift : 160
  samplerate : 16000
---
data:
  SNR :  ['SNR-7','SNR-5','SNR0','SNR5','SNR7','SNR10']
  root: '/home/data/kbh/MCFE/CGMM_RLS_MPDR/train/MFCC/'
  inference: '/home/data/kbh/MCFE/CGMM_RLS_MPDR/inference/MFCC/'

---
log:
  root: '/home/nas/user/kbh/MCFE/'
