gpu: 'cuda:0'
---
feature: 'MFCC' # MFCC, <LMSPC>
---
model:
  type: 'FC' #  FC, DAE
  version : 2
  channels : 2 # noisy, hat_speech, [hat_noise]
  context : 3  # ( conext...  target ...conext )
  fbank : 13
---
train:
  epoch: 1
  batch_size: 10
  num_workers: 1
  summary_interval: 1
  validation_interval: 10
  checkpoint_interval: 100
---
loss:
  type: 'L1' # MSE, L1
---
optim:
  type: "Adam" # Adam
  adam: 0.0001
  adabound:
    initial: 0.001
    final: 0.05
---
scheduler: 
  type: 'Plateau' # Plateau, oneCycle, None
  oneCycle:
    max_lr: 0.0001
  Plateau:
    mode: 'min'
    patience: 2
    factor: 0.5
    min_lr: 0.000005
---
audio:
  frame : 400
  shift : 160
  samplerate : 1600
---
data:
  root: '/home/data/kbh/MCFE/'
---
  log:
    root: '/home/nas/user/kbh/MCFE/'
